##
## See: https://chrony.tuxfamily.org/documentation.html
##

pool time.apple.com
server time.cloudflare.com iburst nts

allow 192.168.0.0/16
allow 10.0.0.0/8
allow 100.64.0.0/10
allow 169.254.0.0/16
allow 172.16.0.0/12
allow 127.0.0.0/8

driftfile /var/lib/chrony/drift
pidfile /var/run/chronyd.pid
logdir /var/log/chrony

dumponexit
dumpdir /var/lib/chrony

makestep 0.3 10
rtcsync
